version: '3.8'

services:
  legalhub:
    build: .
    container_name: legalhub_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - legalhub-network

  db:
    image: postgres:16
    container_name: legalhub_db
    restart: always
    environment:
      POSTGRES_USER: legalhub_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: legalhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legalhub-network

  
  

volumes:
  postgres_data:

networks:
  legalhub-network:
